package Vue;

import javax.swing.JFrame;
import java.awt.event.*;
import java.awt.event.ActionListener;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Dimension;
public class ConnexionInscription extends JFrame{
	/*
	 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
	 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
	 */

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 *
	 * @author antoi
	 */
	    // Variables declaration - do not modify                     
	    private javax.swing.JLabel InscriptionLabel;
	    private javax.swing.JLabel connexionLabel;
	    private javax.swing.JPanel connexionPanel;
	    private javax.swing.JTextField dateNaissanceField;
	    private javax.swing.JLabel dateNaissanceLabel;
	    private javax.swing.JPanel globalPanel;
	    private javax.swing.JButton inscriptionButton;
	    private javax.swing.JPanel inscriptionPanel;
	    private javax.swing.JButton jButton1;
	    private javax.swing.JTextField mailField;
	    private javax.swing.JLabel mailLabel;
	    private javax.swing.JTextField mailinscriptionField;
	    private javax.swing.JLabel mailinscriptionLabel;
	    private javax.swing.JTextField mdpField;
	    private javax.swing.JTextField mdpInscriptionField;
	    private javax.swing.JLabel mdpInscriptionLabel;
	    private javax.swing.JLabel mdpLabel;
	    private javax.swing.JTextField nomField;
	    private javax.swing.JLabel nomLabel;
	    private javax.swing.JTextField prenomField;
	    private javax.swing.JLabel prenomLabel;
	    /**
	     * Creates new form VueIncriptionConnexion
	     */
	    public ConnexionInscription() {
	        initComponents();
	    }

	    /**
	     * This method is called from within the constructor to initialize the form.
	     * WARNING: Do NOT modify this code. The content of this method is always
	     * regenerated by the Form Editor.
	     */
	    @SuppressWarnings("unchecked")
	    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	    private void initComponents() {

	        globalPanel = new javax.swing.JPanel();
	        InscriptionLabel = new javax.swing.JLabel();
	        connexionLabel = new javax.swing.JLabel();
	        connexionPanel = new javax.swing.JPanel();
	        mailLabel = new javax.swing.JLabel();
	        mdpLabel = new javax.swing.JLabel();
	        mdpField = new javax.swing.JTextField();
	        mailField = new javax.swing.JTextField();
	        inscriptionButton = new javax.swing.JButton();
	        inscriptionPanel = new javax.swing.JPanel();
	        nomLabel = new javax.swing.JLabel();
	        nomField = new javax.swing.JTextField();
	        prenomField = new javax.swing.JTextField();
	        prenomLabel = new javax.swing.JLabel();
	        dateNaissanceLabel = new javax.swing.JLabel();
	        dateNaissanceField = new javax.swing.JTextField();
	        mailinscriptionLabel = new javax.swing.JLabel();
	        mailinscriptionField = new javax.swing.JTextField();
	        mdpInscriptionLabel = new javax.swing.JLabel();
	        mdpInscriptionField = new javax.swing.JTextField();
	        jButton1 = new javax.swing.JButton();

	        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

	        InscriptionLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
	        InscriptionLabel.setText("Inscription");

	        connexionLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
	        connexionLabel.setText("Connexion");

	        mailLabel.setText("mail:");

	        mdpLabel.setText("mot de passe:");

	        mdpField.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                mdpFieldActionPerformed(evt);
	            }
	        });

	        mailField.setText("Entrez votre adresse mail");
	        mailField.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                mailFieldActionPerformed(evt);
	            }
	        });

	        javax.swing.GroupLayout connexionPanelLayout = new javax.swing.GroupLayout(connexionPanel);
	        connexionPanel.setLayout(connexionPanelLayout);
	        connexionPanelLayout.setHorizontalGroup(
	            connexionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(connexionPanelLayout.createSequentialGroup()
	                .addContainerGap()
	                .addGroup(connexionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(connexionPanelLayout.createSequentialGroup()
	                        .addComponent(mdpLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
	                        .addComponent(mdpField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
	                    .addGroup(connexionPanelLayout.createSequentialGroup()
	                        .addComponent(mailLabel)
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                        .addComponent(mailField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
	                .addContainerGap())
	        );
	        connexionPanelLayout.setVerticalGroup(
	            connexionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(connexionPanelLayout.createSequentialGroup()
	                .addGap(22, 22, 22)
	                .addGroup(connexionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(mailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(mailLabel))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addGroup(connexionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(mdpLabel)
	                    .addComponent(mdpField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addContainerGap(68, Short.MAX_VALUE))
	        );

	        inscriptionButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
	        inscriptionButton.setText("S'inscrire");
	        inscriptionButton.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                inscriptionButtonActionPerformed(evt);
	            }
	        });

	        nomLabel.setText("Nom:");

	        prenomField.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                prenomFieldActionPerformed(evt);
	            }
	        });

	        prenomLabel.setText("Prenom:");

	        dateNaissanceLabel.setText("Date de naissance:");

	        dateNaissanceField.setText("jj/mm/aaaa");
	        dateNaissanceField.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                dateNaissanceFieldActionPerformed(evt);
	            }
	        });

	        mailinscriptionLabel.setText("Mail:");

	        mailinscriptionField.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                mailinscriptionFieldActionPerformed(evt);
	            }
	        });

	        mdpInscriptionLabel.setText("Mot de passe:");

	        mdpInscriptionField.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                mdpInscriptionFieldActionPerformed(evt);
	            }
	        });

	        javax.swing.GroupLayout inscriptionPanelLayout = new javax.swing.GroupLayout(inscriptionPanel);
	        inscriptionPanel.setLayout(inscriptionPanelLayout);
	        inscriptionPanelLayout.setHorizontalGroup(
	            inscriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(inscriptionPanelLayout.createSequentialGroup()
	                .addContainerGap()
	                .addGroup(inscriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inscriptionPanelLayout.createSequentialGroup()
	                        .addGroup(inscriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addComponent(nomLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(prenomLabel))
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                        .addGroup(inscriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
	                            .addComponent(prenomField, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
	                            .addComponent(nomField)))
	                    .addGroup(inscriptionPanelLayout.createSequentialGroup()
	                        .addGroup(inscriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addComponent(dateNaissanceLabel)
	                            .addComponent(mailinscriptionLabel)
	                            .addComponent(mdpInscriptionLabel))
	                        .addGap(29, 29, 29)
	                        .addGroup(inscriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addComponent(mdpInscriptionField)
	                            .addComponent(dateNaissanceField, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
	                            .addComponent(mailinscriptionField))))
	                .addContainerGap())
	        );
	        inscriptionPanelLayout.setVerticalGroup(
	            inscriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(inscriptionPanelLayout.createSequentialGroup()
	                .addContainerGap()
	                .addGroup(inscriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(nomLabel)
	                    .addComponent(nomField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addGroup(inscriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(prenomField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(prenomLabel))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addGroup(inscriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addComponent(dateNaissanceLabel)
	                    .addComponent(dateNaissanceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addGroup(inscriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(mailinscriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(mailinscriptionLabel))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                .addGroup(inscriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(mdpInscriptionLabel)
	                    .addComponent(mdpInscriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
	        );

	        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
	        jButton1.setText("Se Connecter");
	        jButton1.addActionListener(new java.awt.event.ActionListener() {
	            public void actionPerformed(java.awt.event.ActionEvent evt) {
	                jButton1ActionPerformed(evt);
	            }
	        });

	        javax.swing.GroupLayout globalPanelLayout = new javax.swing.GroupLayout(globalPanel);
	        globalPanel.setLayout(globalPanelLayout);
	        globalPanelLayout.setHorizontalGroup(
	            globalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(globalPanelLayout.createSequentialGroup()
	                .addGap(87, 87, 87)
	                .addComponent(InscriptionLabel)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                .addComponent(connexionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGap(69, 69, 69))
	            .addGroup(globalPanelLayout.createSequentialGroup()
	                .addContainerGap()
	                .addComponent(inscriptionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
	                .addComponent(connexionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addGap(16, 16, 16))
	            .addGroup(globalPanelLayout.createSequentialGroup()
	                .addGap(90, 90, 90)
	                .addComponent(inscriptionButton)
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                .addComponent(jButton1)
	                .addGap(55, 55, 55))
	        );
	        globalPanelLayout.setVerticalGroup(
	            globalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(globalPanelLayout.createSequentialGroup()
	                .addContainerGap()
	                .addGroup(globalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
	                    .addComponent(InscriptionLabel)
	                    .addComponent(connexionLabel))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
	                .addGroup(globalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addComponent(inscriptionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(connexionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addGap(18, 18, 18)
	                .addGroup(globalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addComponent(jButton1)
	                    .addComponent(inscriptionButton))
	                .addContainerGap(10, Short.MAX_VALUE))
	        );

	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	        getContentPane().setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addGap(57, 57, 57)
	                .addComponent(globalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addContainerGap(63, Short.MAX_VALUE))
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addGap(35, 35, 35)
	                .addComponent(globalPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
	                .addContainerGap(49, Short.MAX_VALUE))
	        );

	        pack();
	    }// </editor-fold>                        

	    private void inscriptionButtonActionPerformed(java.awt.event.ActionEvent evt) {                                                  
	        // TODO add your handling code here:
	    }                                                 

	    private void mdpFieldActionPerformed(java.awt.event.ActionEvent evt) {                                         
	        // TODO add your handling code here:
	    }                                        

	    private void dateNaissanceFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                   
	        // TODO add your handling code here:
	    }                                                  

	    private void prenomFieldActionPerformed(java.awt.event.ActionEvent evt) {                                            
	        // TODO add your handling code here:
	    }                                           

	    private void mailFieldActionPerformed(java.awt.event.ActionEvent evt) {                                          
	        // TODO add your handling code here:
	    }                                         

	    private void mailinscriptionFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                     
	        // TODO add your handling code here:
	    }                                                    

	    private void mdpInscriptionFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                    
	        // TODO add your handling code here:
	    }                                                   

	    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
	        // TODO add your handling code here:
	    }                                        

	    /**
	     * @param args the command line arguments
	     */
	   

	    // End of variables declaration                   
	}

